version: '3.1'

services:
  db:
    image: mariadb:latest
    container_name: myMariaDB
    restart: always
    ports:
      - '3306:3306'
    environment:
      MARIADB_ROOT_PASSWORD: my-secret-pw
      MARIADB_DATABASE: yamda-go
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - '8080:8080'