on: [push, pull_request]
name: Test
jobs:
  Build:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - name: Build the docker-compose stack
      run: docker-compose -f "docker-compose.yaml" up -d --build
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Fetch Repository
      uses: actions/checkout@v2
    - name: Run Test
      run: go test ./... -v -race
